use_frameworks!

target 'MockNStub_Example' do
  pod 'MockNStub', :path => '../'

  target 'MockNStub_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
