use_frameworks!

target 'MockNStub_Example' do
  pod 'MockNStub', :path => '../'

  target 'MockNStub_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3'
    pod 'QuickGWT', '~> 1'
    pod 'Nimble', '~> 7.0.2'
  end
end
